meals/urls.py
from django.urls import path

from meals.views import (
    MealListView,
    MealDetailView,
    MealDeleteView,
    MealCreateView,
    MealUpdateView,
)

urlpatterns = [
    path("", MealListView.as_view(), name="meals_list"),
    path("<int:pk>/", MealDetailView.as_view(), name="meal_detail"),
    path("new/", MealCreateView.as_view(), name="meal_new"),
    path("<int:pk>/edit/", MealUpdateView.as_view(), name="meal_edit"),
    path("<int:pk>/delete/", MealDeleteView.as_view(), name="meal_delete"),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("meals/", include("meals.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meals/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class Meal(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField()
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="meals",
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField("recipes.Recipe", related_name="recipes")

    def get_queryset(self):
        return Meal.objects.filter(owner=self.request.user)

    def __str__(self):
        return self.name

meals/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from meals.models import Meal

# Create your views here.


class MealListView(LoginRequiredMixin, ListView):
    model = Meal
    template_name = "meals/list.html"
    paginate_by = 2

    def get_queryset(self):
        return Meal.objects.filter(owner=self.request.user)


class MealDetailView(LoginRequiredMixin, DetailView):
    model = Meal
    template_name = "meals/detail.html"

    def get_queryset(self):
        return Meal.objects.filter(owner=self.request.user)


class MealCreateView(LoginRequiredMixin, CreateView):
    model = Meal
    template_name = "meals/new.html"
    fields = ["name", "date", "recipes"]

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("my_model_detail", pk=plan.id)


class MealUpdateView(LoginRequiredMixin, UpdateView):
    model = Meal
    template_name = "meals/edit.html"
    fields = ["name", "date"]

    def get_queryset(self):
        return Meal.objects.filter(owner=self.request.user)

    def get_success_url(self) -> str:
        return reverse_lazy("meal_detail", args=[self.object.id])


class MealDeleteView(LoginRequiredMixin, DeleteView):
    model = Meal
    template_name = "meals/delete.html"
    success_url = reverse_lazy("meals_list")

    def get_queryset(self):
        return Meal.objects.filter(owner=self.request.user)

meals/templates/meals/delete.html
{% extends 'base.html' %}
{% block content %}
  <main>
    <div class="delete-form">
      <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ meals.name}}?</p>
        {{ form.as_p }}
        <div>
          <button class="button">Delete</button>
        </div>
      </form>
    </div>
  </main>
  {% endblock content %}

meals/templates/meals/detail.html
{% extends 'base.html' %}
{% load markdownify %}
{% block pagination %}
  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}
      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>
      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
{% endblock pagination %}

{% block content %}
<div>
  <a href="{% url 'meal_edit' meal.id %}"><button>Edit</button></a>
  <a href="{% url 'meal_delete' meal.id %}"><button>Delete</button></a>
</div>
<main>
  <h1>Recipes for {{ meal.date }}</h1>
  {% for recipe in meal.recipes.all %}
  <p>
    <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name}}</a>
  </p>
  {% endfor %}
</main>
{% endblock content %}

meals/templates/meals/edit.html
{% extends 'base.html' %}
{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
  </main>
  {% endblock content %}

meals/templates/meals/list.html
{% extends 'base.html' %}

{% block pagination %}
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>

    </div>
{% endblock pagination %}

{% block content %} 
 <form method="post">
   <a href="{% url 'meal_new' %}">Create</a>
 </form>
  <main class="recipe-grid">
    {% for meal in meal_list %}
      <div class="recipe-card">
        <h2 class="recipe-card-title">
          <a href="{% url 'meal_detail' meal.pk %}">{{ meal.name }}</a>
        </h2>
        {% for recipe in meal.recipes.all %}
        <p>
          <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name}}</a>
        </p>
        {% endfor %}
      </div>
      {% empty %}
      <div>
        <h1>No meal plans, yet</h1>
        <p>
          Would you like to create one?
        </p>
        <p>
          <a href="{% url 'meal_new' %}">Create meal plan</a>
        </p>
      </div>
    {% endfor %}
  </main>
{% endblock content %}

meals/templates/meals/new.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <a href="{% url 'meals_list' %}"><button class="button">Create</a>
      </div>
    </form>
  </main>
{% endblock %}